sudo: required

language: perl
perl:
  - "5.22"

services:
  - docker

install:
  - cpanm --installdeps .

script:
  - perl Makefile.PL
  - make
  - make test
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [[ $TRAVIS_BRANCH =~ ^v[0-9.]+$ ]]; then echo ${TRAVIS_BRANCH#v}; else echo $TRAVIS_BRANCH; fi`
  - docker build -f docker-image/Dockerfile -t $DOCKER_REPO:$TAG docker-image
  - if [[ $TRAVIS_BRANCH =~ ^v[0-9.]+$ ]]; then docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:latest; fi
  - docker push $DOCKER_REPO
