sudo: required

language: perl
perl:
  - "5.22"

services:
  - docker

install:
  - cpanm --installdeps .

script:
  - perl Makefile.PL
  - make
  - make test
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f docker-image/Dockerfile -t $DOCKER_REPO:$TRAVIS_BRANCH docker-image
  - docker tag $DOCKER_REPO:$TRAVIS_BRANCH $DOCKER_REPO:latest
  - docker push $DOCKER_REPO