sudo: required

language: perl
perl:
  - "5.22"

services:
  - docker

install:
  - cpanm --installdeps .

script:
  - perl Makefile.PL
  - make
  - make test

after_success:
  - echo "Branch: $TRAVIS_BRANCH\nTag: $TRAVIS_TAG"
  - if [[ $TRAVIS_BRANCH = "master" && $TRAVIS_TAG && $TRAVIS_TAG =~ "^v[0-9.]+$" ]]; then sh ".travis_build_docker_image.sh"; fi